name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert pytest

      - name: Run all notebooks
        run: |
          mkdir -p output_notebooks
          for nb in *.ipynb; do
            echo "Running $nb"
            jupyter nbconvert --to notebook --execute "$nb" --output "output_notebooks/${nb%.ipynb}_executed.ipynb"
          done

      - name: Run pytest (if available)
        run: |
          if [ -d "tests" ]; then
            pytest -v
          else
            echo "No tests folder found, skipping pytest"
          fi
